### ISSUE TITLE
Sign me up please!

### ISSUE THREAD

**Issue by nayaks16** [pharmaR/regulatory-r-repo-wg#46]
Hi

Could you sign me up please as a rep. from Pfizer R community.

Thanks

**Comment by dgkf** [comment]
Sure thing, we'd love to have you onboard! Tagging @Crosita to help get you all the onboarding materials and add you to our meetings.

**Comment by nayaks16** [comment]
Thank you Doug!

**Comment by dgkf** [comment]
Hey @nayaks16 - I just wanted to follow up with you. Did you ever get our onboarding materials? Regardless, we'll be hosting an all-hands on April 27th which will be a bit of a "relaunch" now that we've done some requirements gathering and to kick off the next phase of the project.

**Comment by nayaks16** [comment]
Hi Doug

Thanks for following up. No, I did not get any onboarding materials.

Please feel free to forward them to me, I will make every attempt to attend the onboarding meeting.

Best
Satya

From: Doug Kelkhoff ***@***.***>
Sent: Wednesday, April 12, 2023 11:25 AM
To: pharmaR/regulatory-r-repo-wg ***@***.***>
Cc: Nayak, Satyaprakash ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pharmaR/regulatory-r-repo-wg] Sign me up please! (Issue #46)


Hey @nayaks16<https://urldefense.com/v3/__https:/github.com/nayaks16__;!!H9nueQsQ!87sGZB-HX7ViCPxFP7F5p6UmUKYSdnOGGp-Qtd7vmZ_E7r4FOlzRVP85GN0rrXGk8_KWIlP8aTot8fSFnNORuDdw_Pd-52er$> - I just wanted to follow up with you. Did you ever get our onboarding materials? Regardless, we'll be hosting an all-hands on April 27th which will be a bit of a "relaunch" now that we've done some requirements gathering and to kick off the next phase of the project.

**Comment by dgkf** [comment]
Okay, let me make sure we get you connected. I think Crosita is OOO for the next week or so, so I won't bother her to distribute info to you.

Please email me at <img width="179" alt="image" src="https://user-images.githubusercontent.com/18220321/200019988-847a56ec-14be-4750-b1b0-94526f7698ed.png"> so that I can share google doc access to you and I'll pass along some onboarding tasks. Once I have your email address I'll also add you to our upcoming all hands event.

**Comment by dgkf** [comment]
Hi @nayaks16 - just reaching out again. I don't think I've received an email with your contact info yet. If you're still looking to get involved, can you please email at <img alt="image" width="179" src="https://user-images.githubusercontent.com/18220321/200019988-847a56ec-14be-4750-b1b0-94526f7698ed.png"> so that we can send you an invite for our upcoming all hands meeting on Thursday.
